apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
  labels:
    app: green-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: green-deployment
  template:
    metadata:
      labels:
        app: green-deployment 
    spec:
      containers:
      - name: green-apps
        image: green_service:v1
        ports:
        - containerPort: 8081
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi