apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
  labels:
    app: green-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: green-deployment
  template:
    metadata:
      labels:
        app: green-deployment 
    spec:
      containers:
      - name: green-apps
        image: green_service:v1
        ports:
        - containerPort: 8081