apiVersion: v1
kind: Service
metadata:
  name: green-service
  labels: 
    app: green-deployment
spec:
  selector:
    app: green-deployment
  ports:
  - name: http-port
    port: 9001
    targetPort: 8081
