apiVersion: v1
kind: Service
metadata:
  name: blue-service
  labels: 
    app: blue-deployment
spec:
  selector:
    app: blue-deployment
  ports:
  - name: http-port
    port: 9000
    targetPort: 8080
