apiVersion: v1
kind: Service
metadata:
  name: red-service
  labels: 
    app: red-deployment
spec:
  selector:
    app: red-deployment
  ports:
  - name: http-port
    port: 9002
    targetPort: 8082
